### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by kisyular** [kisyular/MI-449-SS17-740-css-frameworks-p1twXJ#1]
@egillespie Can you take a look at this? It's [hosted here](https://kisyular.github.io/MI-449-SS17-740-css-frameworks-p1twXJ/) and meets the following criteria:

- [x] Include the CSS and JS for Bootstrap 3 (not 4) in the page (including the "jQuery" dependency)
- [x] Use the `container` class to center your page content
- [x] Use a `navbar` class to display the name of your site and a list of at least 3 links (to past projects, or anything else) at the top of your page
- [x] Split your main content into 2 columns on large (`lg`) and medium (`md`) sized screens, but collapse them on top of each other on small (`sm`) and extra small (`xs`) screens
- [x] Use a `thumbnail` class on an at least one image in your page

**Comment by egillespie** [comment]
Wow, that's a nice looking site! :coffee: 

It looks like you are using Skeleton.css' styles for your columns, though. Take a look at lines 36 and 50 of `index.html`. Instead of using `one-half`, `one-third`, and `column`, can you figure out the Bootstrap equivalent?

Another small detail is you don't have a name for your site in the navbar. How am I going to tell all my friends about this hot new place to buy coffee? :smile: 

Comment back here after you've made those two changes and I'll take another look. Feel free to ask for pointers if you need help with using Bootstrap's column classes, too!

Thanks!

**Comment by kisyular** [comment]
@egillespie  I fixed the suggested issues. Kindly let me know if there is more issue to correct. Thank you for your help

**Comment by egillespie** [comment]
Much better! One last thing: the switch from 2-column to 1-column should happen when the page width becomes less than 992px.

Check out [these examples](http://getbootstrap.com/css/#grid-example-mixed) and see if you can figure it out. The style classes for your `div`s should represent how many columns small displays will use (12) and how many columns medium displays will use (6).

After you’ve made your changes and pushed them to GitHub, comment here and I’ll take another look.

Thanks!

**Comment by kisyular** [comment]
@egillespie. I made the necessary changes.

Thank you

**Comment by egillespie** [comment]
Niiiiiice. The images look great as they resize to lower device widths! :shipit:
